[package]
name = "path-to-regexp"
version = "0.1.0"
authors = ["Arkadiusz Miszczyszyn <arkadiusz.miszczyszyn@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1.1.2"
log = "0.4"
pretty_env_logger = "0.3.0"