[package]
name = "path_to_regexp"
version = "0.1.0"
authors = ["Arkadiusz Miszczyszyn <arkadiusz.miszczyszyn@gmail.com>"]
edition = "2019"
include = [
    "**/*.rs",
    "Cargo.toml",
]

[dependencies]
regex = "1.1.2"
log = "0.4"
pretty_env_logger = "0.3.0"
